# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
<<<<<<< HEAD
    locale: 'fr'
    avatar_directory: '%kernel.project_dir%/public/uploads/avatar'
    bird_directory: '%kernel.project_dir%/public/uploads/bird'
=======
    locale: 'en'
>>>>>>> 8f51665e4a72d4a1361dc55d5a0c736f5236a534

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
<<<<<<< HEAD
    app.nao.file_uploader:
        class: App\Services\FileUploader
        autowire: true
        public: true
        arguments:
            - $avatarDirectory: '%avatar_directory%'
            - $birdDirectory: '%bird_directory%'

    app.nao.user_manager:
        class: App\Services\UserManager
        autowire: true
        public: true

    app.nao.mailer:
        class: App\Services\Mailer
        autowire: true
        public: true
        arguments:
            - '@mailer'
=======
    app.nao_manager:
        class: App\Services\NAOManager
        autowire: true
        public: true

    app.nao_capture_manager:
        class: App\Services\Capture\NAOCaptureManager
        autowire: true
        public: true

    app.nao_count_captures:
        class: App\Services\Capture\NAOCountCaptures
        autowire: true
        public: true

    app.nao_comment_manager:
        class: App\Services\Comment\NAOCommentManager
        autowire: true
        public: true

    app.nao_count_comments:
        class: App\Services\Comment\NAOCountComments
        autowire: true
        public: true

    app.nao_show_map:
        class: App\Services\Capture\NAOShowMap
        autowire: true
        public: true

    app.nao_pagination:
        class: App\Services\NAOPagination
        autowire: true
        public: true
>>>>>>> 8f51665e4a72d4a1361dc55d5a0c736f5236a534
    
    app.nao_frontend_bird_controller:
        class: App\Controller\Frontend\BirdController
        autowire: true
        public: true

    app.nao_frontend_capture_controller:
        class: App\Controller\Frontend\CaptureController
        autowire: true
        public: true

    app.nao_frontend_home_controller:
        class: App\Controller\Frontend\HomeController
        autowire: true
        public: true

    app.nao_backend_capture_controller:
        class: App\Controller\Backend\CaptureController
        autowire: true
        public: true

    app.nao_backend_adminspace_controller:
        class: App\Controller\Backend\AdminSpaceController
        autowire: true
        public: true

    app.nao_backend_useraccount_controller:
        class: App\Controller\Backend\UserAccountController
        autowire: true
        public: true